## Exam 1
#### Name: Zach Hatzenbeller
#### Date: 10/07/2025
#### Course: EN.625.661.83.FA25


In [127]:
import pandas as pd 
import numpy as np

# Import the f-distribution and t-distribution
from scipy.stats import f, t

In [128]:
# TABLE B.6 Tube-Flow Reactor Data
# y: NbOCl3 concentration (g-mol/l)
# x1: COCl2 concentration (g-mol/l)
# x2: Space time (sec)
# x3: Molar density (g-mol/l)
# x4: Mole fraction CO2

run_no = np.arange(1, 29)
y = [
    0.000450, 0.000450, 0.000473, 0.000507, 0.000457, 0.000452, 0.000453, 0.000426, 0.001215, 0.001256, 0.001145, 0.001085, 0.001066, 0.001111, 0.001364, 0.001254, 0.001396, 0.001575, 0.001615, 0.001733, 0.002753, 0.003186, 0.003227, 0.003469, 0.001911, 0.002588, 0.002635, 0.002725,
]
x1 = [
    0.0105, 0.0110, 0.0106, 0.0116, 0.0121, 0.0123, 0.0122, 0.0122, 0.0123, 0.0122, 0.0094, 0.0100, 0.0101, 0.0099, 0.0110, 0.0117, 0.0110, 0.0104, 0.0067, 0.0066, 0.0044, 0.0073, 0.0078, 0.0067, 0.0091, 0.0079, 0.0068, 0.0065,
]
x2 = [
    90.9, 84.6, 88.9, 488.7, 454.4, 439.2, 447.1, 451.6, 487.8, 467.6, 95.4, 87.1, 82.7, 87.0, 516.4, 488.0, 534.5, 542.3, 98.8, 84.8, 69.6, 436.9, 406.3, 447.9, 58.5, 394.3, 461.0, 469.2,
]
x3 = [
    0.0164, 0.0165, 0.0164, 0.0187, 0.0187, 0.0187, 0.0186, 0.0187, 0.0192, 0.0192, 0.0163, 0.0162, 0.0162, 0.0163, 0.0190, 0.0189, 0.0189, 0.0189, 0.0163, 0.0162, 0.0163, 0.0189, 0.0192, 0.0192, 0.0164, 0.0177, 0.0174, 0.0173,
]
x4 = [
    0.0177, 0.0172, 0.0157, 0.0082, 0.0070, 0.0065, 0.0071, 0.0062, 0.0153, 0.0129, 0.0354, 0.0342, 0.0323, 0.0337, 0.0161, 0.0149, 0.0163, 0.0164, 0.0379, 0.0360, 0.0327, 0.0263, 0.0200, 0.0197, 0.0331, 0.0674, 0.0770, 0.0780,
]

data = {
    "Run No.": run_no,
    "y": y,
    "x1": x1,
    "x2": x2,
    "x3": x3,
    "x4": x4,
}

# Create a DataFrame
df = pd.DataFrame(data)

# Randomly select 20 runs and create a table with only the Run No., y, x1, and x4 columns
rand_selection = df.sample(n=20, random_state=42)
q2_table = rand_selection[['Run No.', 'y', 'x1', 'x4']]
q2_table

Run No.         y      x1      x4
9        10  0.001256  0.0122  0.0129
25       26  0.002588  0.0079  0.0674
8         9  0.001215  0.0123  0.0153
21       22  0.003186  0.0073  0.0263
0         1  0.000450  0.0105  0.0177
12       13  0.001066  0.0101  0.0323
17       18  0.001575  0.0104  0.0164
22       23  0.003227  0.0078  0.0200
11       12  0.001085  0.0100  0.0342
13       14  0.001111  0.0099  0.0337
15       16  0.001254  0.0117  0.0149
1         2  0.000450  0.0110  0.0172
4         5  0.000457  0.0121  0.0070
5         6  0.000452  0.0123  0.0065
2         3  0.000473  0.0106  0.0157
16       17  0.001396  0.0110  0.0163
23       24  0.003469  0.0067  0.0197
3         4  0.000507  0.0116  0.0082
26       27  0.002635  0.0068  0.0770
24       25  0.001911  0.0091  0.0331

### Estimate the Regression Coefficients using matrix form

In [129]:
X_reg = q2_table[["x1", "x4"]].values
y = q2_table["y"].values

X = np.column_stack((np.ones(X_reg.shape[0]), X_reg))  # Add intercept term

# Degrees of freedom
dfn = X.shape[1] - 1  # Degrees of freedom for the numerator (number of predictors)
dfd = len(y) - X.shape[1]  # Degrees of freedom for the denominator (n - k - 1)

beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Estimated coefficients (beta):", beta)

Estimated coefficients (beta): [ 0.00714737 -0.53719203 -0.01026343]


### Calculate the sum of squares and residual variance for the model

In [130]:
y_bar = np.mean(y)
y_pred = X @ beta
sst = np.sum((y - y_bar) ** 2)
ssr = np.sum((y_pred - y_bar) ** 2)
sse = np.sum((y - y_pred) ** 2)
res_variance = sse / (len(y) - X.shape[1])
print("Total Sum of Squares (SST):", sst)
print("Regression Sum of Squares (SSR):", ssr)
print("Error Sum of Squares (SSE):", sse)
print("Residual Variance (s^2):", res_variance)

Total Sum of Squares (SST): 1.950171855e-05
Regression Sum of Squares (SSR): 1.5011980034919443e-05
Error Sum of Squares (SSE): 4.4897385150807346e-06
Residual Variance (s^2): 2.6410226559298437e-07


### Calculate the Covariance Matrix, Standard Error Vector, t-statistics, and p-values for each Regressor

In [131]:
variance = res_variance * np.linalg.inv(X.T @ X)
std_error = np.sqrt(np.diag(variance))
print("Variance-Covariance Matrix of coefficients:\n", variance)
print()
print("Standard Errors of coefficients:", std_error)

Variance-Covariance Matrix of coefficients:
 [[ 1.03227437e-06 -8.47324276e-05 -6.76036499e-06]
 [-8.47324276e-05  7.22000895e-03  4.90566796e-04]
 [-6.76036499e-06  4.90566796e-04  7.41281085e-05]]

Standard Errors of coefficients: [0.00101601 0.08497064 0.00860977]


In [132]:
t_stats = beta / std_error
print("t-statistics for each coefficient:", t_stats)

t-statistics for each coefficient: [ 7.03474597 -6.32209024 -1.19206815]


In [133]:
# Use the t-distribution to find the two-tailed p-values
p_value_t = [t.sf(abs(ti), df=dfd) * 2 for ti in t_stats]
print("p-values for each coefficient:", p_value_t)

p-values for each coefficient: [2.0063823222649566e-06, 7.654396730585151e-06, 0.2496099920360971]


### Calculate the F-statistic and p-value from the f distribution

In [134]:
f_statistic = ((ssr/dfn) / res_variance)
# Use the F-distribution to find the p-value
p_value_f = f.sf(f_statistic, dfn, dfd)
print("F-test statistic:", f_statistic)
print("p-value:", p_value_f)

F-test statistic: 28.420771024461484
p-value: 3.786686857105349e-06


### Correlation between regressors

In [135]:
cov_beta = res_variance * np.linalg.inv(X.T @ X)
corr = cov_beta[1,2] / np.sqrt(cov_beta[1,1]*cov_beta[2,2])

print("Covariance matrix between regressors:\n", cov_beta)
print()
print("Correlation between regressors x1 and x4:", corr)

Covariance matrix between regressors:
 [[ 1.03227437e-06 -8.47324276e-05 -6.76036499e-06]
 [-8.47324276e-05  7.22000895e-03  4.90566796e-04]
 [-6.76036499e-06  4.90566796e-04  7.41281085e-05]]

Correlation between regressors x1 and x4: 0.6705602769084185
