In [7]:
import numpy as np
from scipy.linalg import lu

In [8]:
A = np.array(
    [[2,3,1,-11,1],
    [5,-2,5,-4,5],
    [1,-1,3,-3,3],
    [3,4,-7,2,-7]]
)
pl, u = lu(A, permute_l=True)

In [11]:
np.linalg.matrix_rank(A)

3

In [9]:
pl

array([[ 0.4       ,  0.73076923,  1.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.2       , -0.11538462,  0.13414634,  1.        ],
       [ 0.6       ,  1.        ,  0.        ,  0.        ]])

In [10]:
u

array([[ 5.00000000e+00, -2.00000000e+00,  5.00000000e+00,
        -4.00000000e+00,  5.00000000e+00],
       [ 0.00000000e+00,  5.20000000e+00, -1.00000000e+01,
         4.40000000e+00, -1.00000000e+01],
       [ 0.00000000e+00,  0.00000000e+00,  6.30769231e+00,
        -1.26153846e+01,  6.30769231e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.42821989e-16,  0.00000000e+00]])

In [27]:
aug = np.array([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6],
    [4,5,6,7],
])

aug2 = np.array([
    [1,1/2,1/3,1/4],
    [1/2,1/3,1/4,1/5],
    [1/3,1/4,1/5,1/6],
    [1/4,1/5,1/6,1/7],
])

np.linalg.matrix_rank(aug2)

4

In [23]:
q9 = np.array([
    [1,2],
    [3,4]
])

q9_2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

np.linalg.matrix_rank(q9_2)

2

In [32]:
q6 = np.array([
    [2,3,1,-11,1],
    [5,-2,5,-4,5],
    [1,-1,3,-3,3],
    [3,4,-7,2,-7],
])

aug = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6],
])

q6_b = np.array([4,5,6,7])

# np.linalg.solve(aug,q6_b)
np.linalg.matrix_rank(q6)

3

In [24]:

q9_2 = np.array([
    [2,3,1,-11,1],
    [5,-2,5,-4,5],
    [1,-1,3,-3,3],
    [3,4,-7,2,-7],
])

np.linalg.matrix_rank(q9_2)

3

In [35]:
# circuit problem

aug = np.array([
    [-1, 1, 1],
    [4, 12, 0],
    [0, 12, 8]
])

q6_b = np.array([0,12,24])

np.linalg.solve(aug,q6_b)

array([2.14285714, 1.71428571, 0.42857143])