# Module 2 - Activity

During this module we discussed the covariance matrix, which is a matrix that describes the variance and covariance between multiple variables. 

- Reference the lecture notes for more details on the covariance matrix.

In this activity you will be creating a covariance matrix, without the use of any built in method, for the following data set.

In [1]:
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()

# iris is a Bunch object, similar to a dictionary, containing data and metadata
# The features (measurements) of the Iris dataset are stored in 'data'
iris_data = iris.data

# The labels (species of each instance) are stored in 'target'
iris_labels = iris.target

# The names of the features and labels are also stored
feature_names = iris.feature_names
label_names = iris.target_names

# To see the shape of the dataset
print("Data shape:", iris_data.shape)  # e.g., (150, 4)
print("Labels shape:", iris_labels.shape)  # e.g., (150,)

# If you want to see the first few entries
print("First 5 rows of data:\n", iris_data[:5])
print("First 5 labels:", iris_labels[:5])


Data shape: (150, 4)
Labels shape: (150,)
First 5 rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
First 5 labels: [0 0 0 0 0]


In [8]:
# Implementation of creating the covariance matrix
import numpy as np

def cov_matrix(data):
    row, col = data.shape
    cov_mat = np.zeros([col, col])

    for i in range(col):
        i_mean = np.mean(data[:,i])
        for j in range(col):
            j_mean = np.mean(data[:,j])
            cov_mat[i,j] = np.sum((data[:,i] - i_mean) * (data[:,j] - j_mean)) / (row - 1)
    
    return cov_mat

covariance_matrix = cov_matrix(iris_data)
covariance_matrix

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

Please add your Jupyter Notebook to the discussion board found under Module 2. You are encouraged to review other students' submissions to check and discuss differences in your approaches. 